### PR TITLE
Converted to Swift 2.0

### PR DESCRIPTION
**Pull request by VasuLaroiya**
I converted the SwiftSpinner.swift file to Swift 2.0. I also converted the Demo Project to a Xcode 7 project. The pod file wasn’t working for me so I changed it to get the SwiftSpinner from the cocoapod you have setup.

### CODE REVIEW

**Comment by icanzilb** [comment]
I appreciate it but Swift 2.0 is still beta so your changes will break people's projects who are using the latest stable Xcode

**Comment by VasuLaroiya** [comment]
I understand but you can make a new branch for swift 2.0 so people who are using swift 2.0 they can use your project without any worry.

**Comment by icanzilb** [comment]
ok, let me check how can I do that on github

**Comment by icanzilb** [comment]
the project doesn't compile on xcode7, imports some kind of 3rd party libraries, doesn't use the local pod source

**Comment by VasuLaroiya** [comment]
Yeah the pod file you have setup doesn't work. If you link the file SwiftSpinner that is in the main folder it will work.

**Comment by ndmeiri** [comment]
@icanzilb Can we reopen this please? Those of us who are using SwiftSpinner in our Swift 2.0 projects can't compile our projects unless we fork this repo or stop using the control altogether. As @VasuLaroiya mentioned, you can create a branch for just the Swift 2.0 changes.

**Pull request closed without merging**
