### PR TITLE
Updated minimum ios deployment target to iOS 9 to support XCode12.x without warnings

### PR DESCRIPTION
**Pull request by JOyo246**

### CODE REVIEW

**Comment by andreamazz** [comment]
Thank you 👍

**Comment by JOyo246** [comment]
@andreamazz no problem! It was bugging me lol. Also, theres a mention of iOS 8 in the GitHub main Markdown: "fitting iOS 8 design very well."
Along with the about section for the repo: flat and bold design - all iOS 8 latest and greatest"

**Comment by JOyo246** [comment]
@andreamazz one more thing... could you add a version tag for 2.2.0... for everyone using Swift Package Manager 💯

**Comment by andreamazz** [comment]
All done 👍

**Pull request merged**
