### PR TITLE
Swift 2.0

### PR DESCRIPTION
**Pull request by VasuLaroiya**
I removed the pods file and fixed the error you were talking about in your emails. This project should compile and run just fine under Xcode 7 and Swift 2.0.

### CODE REVIEW

**Comment by icanzilb** [comment]
I'm sorry 29 changed files is not what I'm looking for in a pull request. If you want to add Swift 2.0 support change only the relevant lines

**Comment by VasuLaroiya** [comment]
Okay I’ll fix that then.

**Comment by buildreactive** [comment]
Is Swift 2 support going anywhere?

**Comment by icanzilb** [comment]
Swift 2 will be supported when it's released, I can't upgrade to 2.0 when people's release code is still on 1.2 or am I looking at this the wrong way?

**Comment by VasuLaroiya** [comment]
You can create a new branch so that users can use this project in their app. This way people who are on Swift 1.2 can access the master branch and people who are using Swift 2.0 can access the swift-2.0 branch.

**Comment by VasuLaroiya** [comment]
The only reason the pull request is for the master branch is because you don't have a Swift-2.0 branch. Once you create one ill cancel this pull request and send a pull request for that branch.

**Comment by buildreactive** [comment]
In the meantime... I created a fork (as you probably saw) on your latest changes, and have done the same. Pull request created. If you create a branch for swift-2 it would be handy for third parties that are already working in Xcode 7.

**Pull request closed without merging**
