### PR TITLE
endless loanding when showing spinner during hide transition

### PR DESCRIPTION
**Pull request by StoykovPrime**

### CODE REVIEW

**Comment by andreamazz** [comment]
Hi @StoykovPrime 
can you provide more context to this PR? 
Why are you setting a duration of 0.66?

**Comment by StoykovPrime** [comment]
Hi  @andreamazz 

The duration is set to 0.66 because there is enough time for the previous animation to stop and to add new loading spinner to the view. If we call again SwiftSpinner.show(title, animated: animated) we create another one and we are going to be in endless loading screen. So in thus case we call another method SwiftSpinner.show(duration: 0.66, title: title) and it will hide the spinner when the animation is done.

**Comment by ruckus** [comment]
Thanks @StoykovPrime -- I was suffering from this exact issue and I just patched my local source with your diff and I'm good to go!

**Comment by andreamazz** [comment]
Thank you @StoykovPrime 
I'm not a fan of having a hard-coded value like that, but I understand it might be an unfortunate timing issue, so I reckon it'll do until we find a more pragmatic solution.

**Pull request merged**
